### ISSUE TITLE
DNA to DNA indexing and align

### ISSUE THREAD

**Issue by sivasubramanics** [fawaz-dabbaghieh/PanPA#1]
Dear Team,

Thanks for this excellent tool. I was just wondering if you already have a work around for DNA to DNA graph indexing and align instead of proteome graphs. 

Thanks,
Best,
Siva

**Comment by fawaz-dabbaghieh** [comment]
Dear Siva,

Other tools already deal with DNA-to-DNA aligning, like [GraphAligner](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-020-02157-2), [Giraffe](https://github.com/vgteam/vg/wiki/Mapping-short-reads-with-Giraffe), or [minigraph](https://github.com/lh3/minigraph).
These tools are already very efficient and designed for that task.

Best,
Fawaz

**Comment by sivasubramanics** [comment]
Wow, thanks Fawaz, for the quick response.

I appreciate your suggestions. But I was working on a pipeline, where I
would want to generate GFA for isoforms, and map RNAseq reads directly on
those graphs. Just like how you have clustered the proteins -> MSA -> GFA
-> index -> Align. I do not think, the mentioned tools work with mapping
reads on multiple GFA+index just like PanPA.

Thanks again,

Best,
Siva

**Comment by fawaz-dabbaghieh** [comment]
Hi Siva,

Then you can just use PanPA, which also accepts DNA, you just need to add the argument `--dna` to the `align` subcommand when aligning. It doesn't matter for building a GFA or indexing what the sequences are, PanPA works with them as pure strings. I haven't heavily tested it with DNA, so if you face any trouble, please don't hesitate to open an issue again.

Best,
Fawaz

**Comment by sivasubramanics** [comment]
Yeah, I did try the --dna option, but it was trying to translate and align, assuming it as DNA->PROTEIN mapping (attached image for eg).  The read length is 70bp, while the align is translating the read and trying to map it on the proteome graph.
<img width="1213" alt="Screenshot 2023-06-28 at 19 59 33" src="https://github.com/fawaz-dabbaghieh/PanPA/assets/29771707/2b51e6d0-9510-4b45-88da-600ff3127c69">


Maybe we need to build the index as DNA (pan-transcriptome), instead of pan-proteome. 


Thanks,
Siva

**Comment by fawaz-dabbaghieh** [comment]
Oh right, my bad, yes, I need to fix that then and add an option to not translate and actually do pure DNA to DNA alignments, internally, it is already able to do that, but I was always thinking in terms of panproteome and assumed that these other tools are better anyway, so I didn't add an option.
Give me a couple of days and I'll give you a solution back. I'll keep this issue open until I update the code.

**Comment by sivasubramanics** [comment]
Ha, perfect. Thanks a ton.

-
Siva

**Comment by fawaz-dabbaghieh** [comment]
Dear Siva,

I pushed some code changes now. However, I realized that this was already possible but probably not clear and somewhat convoluted, I still need to think of a way to make it clearer for users how to do it.

In order to align DNA sequences against DNA graphs. First, build the graphs from the MSAs and index. When aligning, you need to actually omit the `--dna` flag, this way, PanPA won't try to translate the sequence anymore and just align it as is, and use `--sub_matrix dna` which is basically the edit distance (with a match the score is 1 and mismatch is 0). I would also advise you in this case to change the gap penalty to something lower, e.g. `--gap_score -1`.

Hope this help, if you have any problems or bugs, let me know and maybe send me some sample files to look into.

Best,
Fawaz
